# Generated by Django 3.0.3 on 2020-05-06 00:30

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderBoardRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('score', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TriviaQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(null=True)),
                ('answers', django_mysql.models.ListTextField(models.CharField(max_length=300), max_length=66, size=4)),
                ('category', models.CharField(max_length=300, null=True)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
