# Generated by Django 3.0.3 on 2020-04-26 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='triviaquestion',
            name='category',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='triviaquestion',
            name='question',
            field=models.TextField(null=True),
        ),
    ]
