# Generated by Django 3.0.3 on 2020-05-06 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriviaAnswers',
            fields=[
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='game.TriviaQuestion')),
                ('answer1', models.TextField(null=True)),
                ('answer2', models.TextField(null=True)),
                ('answer3', models.TextField(null=True)),
                ('answer4', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='triviaquestion',
            name='answers',
        ),
    ]
