# Generated by Django 3.0.3 on 2020-05-06 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20200506_2331'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TriviaAnswers',
            new_name='TriviaAnswer',
        ),
    ]
