# Generated by Django 3.0.3 on 2020-05-07 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20200506_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trivia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(null=True)),
                ('category', models.CharField(max_length=300, null=True)),
                ('published', models.BooleanField(default=False)),
                ('answer1', models.TextField(null=True)),
                ('answer2', models.TextField(null=True)),
                ('answer3', models.TextField(null=True)),
                ('answer4', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TriviaAnswer',
        ),
        migrations.DeleteModel(
            name='TriviaQuestion',
        ),
    ]
