# Generated by Django 3.0.3 on 2020-05-05 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_leaderboard'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeaderBoard',
            new_name='LeaderBoardRank',
        ),
    ]
