# Generated by Django 3.0.3 on 2020-05-07 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20200507_0219'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trivia',
            new_name='TriviaQuestion',
        ),
    ]
