# Generated by Django 3.0.3 on 2020-05-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20200505_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboardrank',
            name='date',
            field=models.DateField(),
        ),
    ]
