# Generated by Django 3.0.3 on 2020-05-07 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20200507_0227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='triviaquestion',
            old_name='answer1',
            new_name='choice1',
        ),
        migrations.RenameField(
            model_name='triviaquestion',
            old_name='answer2',
            new_name='choice2',
        ),
        migrations.RenameField(
            model_name='triviaquestion',
            old_name='answer3',
            new_name='choice3',
        ),
        migrations.RenameField(
            model_name='triviaquestion',
            old_name='answer4',
            new_name='choice4',
        ),
        migrations.AddField(
            model_name='triviaquestion',
            name='answer',
            field=models.TextField(null=True),
        ),
    ]
