# Generated by Django 3.0.3 on 2020-05-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20200507_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triviaquestion',
            name='answer',
            field=models.IntegerField(choices=[(0, 'Answer1'), (1, 'Answer2'), (2, 'Answer3'), (3, 'Answer4')], default=1),
        ),
    ]
