# Generated by Django 3.0.3 on 2020-05-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20200507_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triviaquestion',
            name='answer',
            field=models.IntegerField(choices=[(0, 'Choice1'), (1, 'Choice2'), (2, 'Choice3'), (3, 'Choice4')], default=0),
        ),
    ]
