# Generated by Django 3.0.3 on 2020-05-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20200507_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triviaquestion',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='triviaquestion',
            name='choice1',
            field=models.TextField(max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='triviaquestion',
            name='choice2',
            field=models.TextField(max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='triviaquestion',
            name='choice3',
            field=models.TextField(max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='triviaquestion',
            name='choice4',
            field=models.TextField(max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='triviaquestion',
            name='question',
            field=models.TextField(max_length=160, null=True),
        ),
    ]
