# Generated by Django 3.0.3 on 2020-06-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20200507_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardrank',
            name='initials',
            field=models.CharField(default='***', max_length=3),
        ),
    ]
